name: CD app to stg server
on:
  workflow_dispatch: {}
  push:
    branches:
      - "feature/add"

jobs:
  build:
    uses: ./.github/workflows/client.yml
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: staging
    env: # Or as an environment variable
      EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
      HOST_NAME: ${{ secrets.HOST_NAME }}
    steps:
    - name: Deploy to EC2
      uses: actions/cache@v3
      id: get-cache
      with: 
        path: client
        key: client-key
    - name: check cache
      run: env
      
    


